### ISSUE TITLE
Dragon fights are broken

### ISSUE THREAD

**Issue by ghostomar16** [IAFEnvoy/IceAndFire-Fabric#33]
distance, slow down your world pre-generator, or increase the CPU load config.
[00:57:13] [Server thread/WARN]: Too many chunks queued for updating, max queue count [500] ([500] per thread). This may result in holes in your LODs. Please move through the world slower, decrease your vanilla render distance, slow down your world pre-generator, or increase the CPU load config.
[00:57:18] [Server thread/WARN]: Too many chunks queued for updating, max queue count [500] ([500] per thread). This may result in holes in your LODs. Please move through the world slower, decrease your vanilla render distance, slow down your world pre-generator, or increase the CPU load config.
[00:57:24] [Server thread/WARN]: Too many chunks queued for updating, max queue count [500] ([500] per thread). This may result in holes in your LODs. Please move through the world slower, decrease your vanilla render distance, slow down your world pre-generator, or increase the CPU load config.
[00:57:29] [Server thread/WARN]: Too many chunks queued for updating, max queue count [500] ([500] per thread). This may result in holes in your LODs. Please move through the world slower, decrease your vanilla render distance, slow down your world pre-generator, or increase the CPU load config.
[00:58:54] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-4,8]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 28
at net.minecraft.world.chunk.Chunk.getSection(Chunk.java:162) ~[client-intermediary.jar:?]
at net.minecraft.world.chunk.WorldChunk.setBlockState(WorldChunk.java:223) ~[client-intermediary.jar:?]
at net.minecraft.world.chunk.WrapperProtoChunk.setBlockState(WrapperProtoChunk.java:77) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.mimicObject.DhLitWorldGenRegion.setBlockState(DhLitWorldGenRegion.java:198) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at net.minecraft.world.ModifiableWorld.setBlockState(ModifiableWorld.java:15) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.feature.BlockColumnFeature.generate(BlockColumnFeature.java:50) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.feature.Feature.generateIfValid(Feature.java:166) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.feature.ConfiguredFeature.generate(ConfiguredFeature.java:28) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.feature.PlacedFeature.method_39646(PlacedFeature.java:54) ~[client-intermediary.jar:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
at java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180) ~[?:?]
at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature.java:53) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.feature.PlacedFeature.generate(PlacedFeature.java:42) ~[client-intermediary.jar:?]
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:357) ~[client-intermediary.jar:?]
... 8 more
[00:58:57] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:58:57] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[0,8]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:58:57] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:58:57] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-4,9]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:58:58] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:58:58] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-3,9]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:58:58] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:58:58] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-2,9]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:58:59] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:58:59] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[0,9]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:00] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:00] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-3,10]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:00] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:00] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-1,10]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:01] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:01] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-3,11]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:02] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:02] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-1,11]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:03] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:03] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[0,11]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:03] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:03] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-4,12]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[00:59:04] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:04] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[-3,12]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
Clipboard copy at: 17 Aug 2024 00:59:08 +0400
Log upload triggered at: 17 Aug 2024 00:59:09 +0400
Log upload canceled
[00:59:17] [DH-World Gen Thread[0]/INFO]: [STDOUT]: Negative index in crash report handler (0/9)
[00:59:17] [DH-World Gen Thread[0]/WARN]: Unexpected issue when generating features for chunk at pos [C[0,8]], error: [Feature placement].
net.minecraft.util.crash.CrashException: Feature placement
at net.minecraft.world.gen.chunk.ChunkGenerator.generateFeatures(ChunkGenerator.java:377) ~[client-intermediary.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:81) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:722) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:495) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at loaderCommon.fabric.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:94) ~[DistantHorizons-2.1.2-a-1.20.1-forge-fabric.jar:?]
at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException
0 i left the server and went on to another world to see if it was doing it there so logs may be mixed with each other
Recommended to upload it onto mclo.gs, pastebin and so on.
couldent do it so i just sent the whole thing

Checklist
 I don't install Optifine i do not have that installed
 I have installed other mods, yes
[ ]

**Comment by IAFEnvoy** [comment]
Known bug with DH
