### ISSUE TITLE
Worldgen broken at the world border. (fabric server) 

### ISSUE THREAD

**Issue by GabrielaKelly** [IAFEnvoy/IceAndFire-Fabric#54]
### What had happened?
Server crashed due to com.iafenvoy.iceandfire.world.gen.WorldGenDragonCave.method_13151
*What you have done and what happen*
Appearing on world border at 30.000.000 -30.000.000 at overworld
### Mod Version (Include dependencies)
iceandfire-2.1.13-1.20.1-beta-5
~~x.y.z~~
30.000.000 -30.000.000(or a close to it)
### Mod Loader Version
Fabric 0.16.5

### Game Log
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2024-11-01 09:14:16
Description: Feature placement

java.lang.NullPointerException: No chunk exists at [1875000, -1874999]
	at knot//net.minecraft.class_3233.method_8392(class_3233.java:2105)
	at knot//net.minecraft.class_3233.method_8649(class_3233.java:328)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenDragonCave.method_13151(WorldGenDragonCave.java:85)
	at knot//net.minecraft.class_3031.method_40163(class_3031.java:166)
	at knot//net.minecraft.class_2975.method_12862(class_2975.java:28)
	at knot//net.minecraft.class_6796.method_39646(class_6796.java:54)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_6796.method_39648(class_6796.java:53)
	at knot//net.minecraft.class_6796.method_39650(class_6796.java:42)
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.method_12154(class_2806.java:252)
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.minecraft.class_3233.method_8392(class_3233.java:2105)
	at knot//net.minecraft.class_3233.method_8649(class_3233.java:328)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenDragonCave.method_13151(WorldGenDragonCave.java:85)
	at knot//net.minecraft.class_3031.method_40163(class_3031.java:166)
	at knot//net.minecraft.class_2975.method_12862(class_2975.java:28)
	at knot//net.minecraft.class_6796.method_39646(class_6796.java:54)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_6796.method_39648(class_6796.java:53)
	at knot//net.minecraft.class_6796.method_39650(class_6796.java:42)
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.method_12154(class_2806.java:252)
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)

-- Feature --
Details:
	Description: ResourceKey[minecraft:worldgen/placed_feature / iceandfire:lightning_dragon_cave]
Stacktrace:
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.method_12154(class_2806.java:252)
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

-- Generation --
Details:
	CenterX: 1875011
	CenterZ: -1874999
	Seed: 2601882841910681613
Stacktrace:
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.method_12154(class_2806.java:252)
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

-- Chunk to be generated --
Details:
	Location: 1875011,-1874999
	Position hash: -8053059383157693
	Generator: net.minecraft.class_3754@70e7a4e5
Stacktrace:
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

-- Affected level --
Details:
	All players: 1 total; [class_3222['AstoriaLancelot_'/51, l='ServerLevel[world]', x=29999980.24, y=99.00, z=-29999981.02]]
	Chunk stats: 4543
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 37694997 game time, 38133257 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 162774 (now: false), thunder time: 7462 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:900)
	at knot//net.minecraft.class_3176.method_3813(class_3176.java:283)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.6.58-1-lts
	Java Version: 21.0.5, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 1154431376 bytes (1100 MiB) / 1818230784 bytes (1734 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 PRO 4650G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Navi 24 [Radeon RX 6400/6500 XT/6500M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x743f
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: Renoir [Radeon Vega Series / Radeon Vega Mobile Series]
	Graphics card #1 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #1 VRAM (MB): 258.00
	Graphics card #1 deviceId: 0x1636
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 11834.46
	Virtual memory used (MB): 11981.39
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 944.23
	JVM Flags: 5 total; -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=6
	Fabric Mods: 
		attributefix: AttributeFix 21.0.4
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		better_nether_gen: Better Nether Generation 3.1.0
		betterend: Better End 4.0.11
		betternether: Better Nether 9.0.10
		bettervillage: Better village 3.1.0
		botania: Botania 1.20.1-446-FABRIC
			fiber: fiber 0.23.0-2
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		chunksending: Chunksending Mod 1.20.1-2.8
		chunky: Chunky 1.3.146
		clumps: Clumps 12.0.0.4
		connectivity: Connectivity Mod 1.20.1-5.8
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		croptopia: Croptopia 3.0.3
		cupboard: cupboard 1.20.1-2.7
		dimensionalsyncfixes: DimensionalSyncFixes 1.20.1-0.0.2
		endrem: End Remastered 5.2.4
		epherolib: EpheroLib 1.2.0
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabric-language-kotlin: Fabric Language Kotlin 1.12.2+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.9.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.9.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.4
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.2
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 6.0.1
		iceandfire: Ice And Fire 0.6.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			fabric-trade-api: Fabric Trade API 0.1.2
		immersive_aircraft: Immersive Aircraft 1.1.2+1.20.1
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.2.1
		java: OpenJDK 64-Bit Server VM 21
		jupiter: Jupiter 1.0
		libraryferret: Library ferret 4.0.0
		lithium: Lithium 0.11.2
		majruszlibrary: Majrusz Library 7.0.8
		majruszsdifficulty: Majrusz's Progressive Difficulty 1.9.10
		man_of_many_planes: Man of Many Planes 0.2.0+1.20.1
		maxhealthfix: MaxHealthFix 12.0.3
		mc249136: MC-249136 (Fabric) 1.0.2
		minecraft: Minecraft 1.20.1
		mr_true_ending: True Ending: Ender Dragon Overhaul 1-v1.1.0c
		patchouli: Patchouli 1.20.1-84-FABRIC
		recipecooldown: Recipe Cooldown 1.17.1-1.0.0
		skinrestorer: SkinRestorer 2.1.0+1.20-fabric
		spark: spark 1.10.53
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		terralith: Terralith 2.5.4
		toofast: TooFast 1.2.0
		trinkets: Trinkets 3.7.2
		uranus: Uranus 1.7
			sponsor_core: Sponsor Core 1.0.0
	Server Running: true
	Player Count: 1 / 8; [class_3222['AstoriaLancelot_'/51, l='ServerLevel[world]', x=29999980.24, y=99.00, z=-29999981.02]]
	Data Packs: vanilla, fabric, file/datapack.zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

### Checklist

- [ yeah] I don't install Optifine
- [yeah ] I have installed other mods

Some crashed was related to light engnie, but I think I fixed that, and now there is a problem with this mod. Idk how to fix it. It`s a fabric server, not a integrated in a singleplayer.

**Comment by GabrielaKelly** [comment]
updating on the latest version of ice and fire and jupiter not working
