### ISSUE TITLE
java.lang.NullPointerException: No chunk exists at [13, 366]

### ISSUE THREAD

**Issue by CaoTrongThang** [IAFEnvoy/IceAndFire-Fabric#56]
### What had happened?
Crash the game with a crash log

*What you have done and what happen*
I was flying around the world and suddenly got crashed

java.lang.NullPointerException: No chunk exists at [13, 366]
	at knot//net.minecraft.class_3233.method_8392(class_3233.java:4605)
	at knot//net.minecraft.class_3233.method_8624(class_3233.java:415)
	at knot//net.minecraft.class_4538.method_8598(class_4538.java:98)
	at knot//net.minecraft.class_5423.method_8598(class_5423.java:33)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generateEntrance(WorldGenMyrmexHive.java:219)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generatePath(WorldGenMyrmexHive.java:170)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generateRoom(WorldGenMyrmexHive.java:211)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generatePath(WorldGenMyrmexHive.java:179)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generateRoom(WorldGenMyrmexHive.java:202)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generatePath(WorldGenMyrmexHive.java:179)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generateRoom(WorldGenMyrmexHive.java:211)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generatePath(WorldGenMyrmexHive.java:179)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.generateMainRoom(WorldGenMyrmexHive.java:105)
	at knot//com.iafenvoy.iceandfire.world.gen.WorldGenMyrmexHive.method_13151(WorldGenMyrmexHive.java:89)
	at knot//net.minecraft.class_3031.method_40163(class_3031.java:166)
	at knot//net.minecraft.class_2975.method_12862(class_2975.java:28)
	at knot//net.minecraft.class_6796.method_39646(class_6796.java:54)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_6796.method_39648(class_6796.java:53)
	at knot//net.minecraft.class_6796.method_39650(class_6796.java:42)
	at knot//net.minecraft.class_2794.method_12102(class_2794.java:357)
	at knot//net.minecraft.class_2806.method_51375(class_2806.java:108)
	at knot//net.minecraft.class_2806$class_3768.doWork(class_2806.java:309)
	at knot//net.minecraft.class_2806.method_12154(class_2806.java:252)
	at knot//net.minecraft.class_3898.method_17225(class_3898.java:684)
	at knot//com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at knot//net.minecraft.class_3898.method_17224(class_3898.java:673)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at knot//net.minecraft.class_3900.method_17634(class_3900.java:62)
	at knot//net.minecraft.class_3846.method_16907(class_3846.java:91)
	at knot//net.minecraft.class_3846.method_16900(class_3846.java:146)
	at knot//net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	
### Mod Version (Include dependencies)
0.6.5

### Mod Loader Version
0.16.9

### Game Log
https://mclo.gs/4MFVICZ

### Checklist

- [x ] I don't install Optifine
- [x] I have installed other mods

**Comment by IAFEnvoy** [comment]
Same reason: #49
